### ISSUE TITLE
downloading reference

### ISSUE THREAD

**Issue by eirikhoye** [icbi-lab/NeoFuse#8] opened 2021-06-30 11:37 UTC
Hi, I attempted to install NeoFuse on a mac, following the instructions, and when I reach step 1.4 there seems to be an error. I use the command:

`NeoFuse -R -o /Volumes/Backup_Plus/neofuse/reference -n 6 -V GRCh38 --docker 
`
and when it finishes downloading the reference I get the following:

```
2021-06-30 11:21:22 (4.65 MB/s) - 'GRCh38.primary_assembly.genome.fa.gz' saved [844691642]

Jun 30 11:23:17 ..... started STAR run
Jun 30 11:23:17 ... starting to generate Genome files
/usr/local/bin/NeoFuse-download: line 78:    **13 Killed**                  STAR --runMode genomeGenerate --runThreadN $THREADS --genomeDir $INDEXDIR --genomeFastaFiles $OUT"/GRCh38.primary_assembly.genome.fa" --sjdbGTFfile $OUT"/gencode.v31.annotation.gtf"

```

After there is nothing in the reference folder.

**Comment by abyssum** [comment] 2021-06-30 13:51
Hi @eirikhoye,

I cannot reproduce the error locally, I am testing on Ubuntu tho so I will try to test on a macOS as well.
In the meantime, could you paste the hardware specs of your setup (I am guessing that this issue might be connected to your RAM)?

**Comment by eirikhoye** [comment] 2021-06-30 14:16
Indeed, you may well be correct about insufficient ram.

I was hoping to install it locally and upload it to our computing cluster (it does not have internet access for security reasons), but I will try one of our other, less strict, computing clusters to see if it will install there. 

Thanks!

**Comment by abyssum** [comment] 2021-06-30 14:30
Makes sense, you can always download the files locally:
```
wget ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_31/gencode.v31.annotation.gtf.gz
wget ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_31/GRCh38.primary_assembly.genome.fa.gz
```

then scp the files to your HPC and if STAR is installed on a node you can run smth like:
```
STAR --runMode genomeGenerate \
--runThreadN [threads] \
--genomeDir /path/to/outDir/ \
--genomeFastaFiles /path/to/GRCh38.primary_assembly.genome.fa \
--sjdbGTFfile  /path/to/gencode.v31.annotation.gtf
```
This should create the indexed ref files and you'd be able to run NeoFuse (given that the executable exists on the node).
At the moment NeoFuse runs STAR v2.7.1a, so I would strongly recommend indexing the files with the same version if possible.

You can also try to use any STAR indexed reference available to you, as long as there are no version conflicts.

I will leave the issue open for now, until I am able to test this on a mac or you have found a workaround (whichever comes first).

**Comment by abyssum** [comment] 2022-02-17 21:44
Closing the issue since I have no update.

**Closed as completed by abyssum** 2022-02-17 21:44 UTC
